### ISSUE TITLE
Doc文档

### ISSUE THREAD

**Issue by kangjun091120** [OpenXLab-Edu/OpenMMLab-Edu#74]
请问mmedu.readthedocs.io中的文档什么时候更新，谢谢，已经有巨多人将他用做初中教育了

**Comment by JiaYanhao** [comment]
感谢您对mmedu的关注,我们会尽快更新相关文档.请理解,文档的上线需要经过我们多次审核,确定没有问题才可以更新

**Comment by EasonQYS** [comment]
感谢您对mmedu的关注，文档更新将移动到xedu.readthedocs.io，也欢迎您参与到文档的编辑和开发中来。您可以在文档网站的右上角点击“在 GitHub 上修改”就可以参与。期待您的参与！
